Frodriguezhervias/agora 1403 port delegatestatement form from old site to tailwind nextjs
voteagora/agora-next pull request #45
Opened 2024-01-04 23:53 UTC by ferrodri

- Port DelegateStatement Form from old site to Tailwind + NextJS
- Save delegateStatement to postgresql
- Get old delegatestatement from dynamodb

<img width="1512" alt="desktop-preview" src="https://github.com/voteagora/agora-next/assets/29060919/ae5d1a0f-4860-49b6-ad68-b67139330cdf">
<img width="1511" alt="desktop-2" src="https://github.com/voteagora/agora-next/assets/29060919/a4fc8570-0942-4b00-b49b-daec39e67aae">
<img width="1510" alt="desktop-1" src="https://github.com/voteagora/agora-next/assets/29060919/172e00c9-79da-4e10-a434-5047b32f2ca4">

<img width="459" alt="mobile-3" src="https://github.com/voteagora/agora-next/assets/29060919/32d515f9-8ff8-4111-a19d-58491fb59eae">
<img width="421" alt="mobile-1" src="https://github.com/voteagora/agora-next/assets/29060919/bf79c0d6-c4a0-4007-b79e-92ae52943753">
<img width="431" alt="mobile-2" src="https://github.com/voteagora/agora-next/assets/29060919/18708d56-50bf-49ff-bd75-c977f34f93f9">

2024-01-04 23:56 UTC, ferrodri commented
Hi @yitongzhang, please let me know your feedback on the UI, there is still some coding logic left to merge the PR but UI is all set. Tomorrow, I was also thinking about adding a Suspense to the delegateCard while it loads, here is a video with my explanation https://www.loom.com/share/fa81370664cf43baa44a729e96aa8b80?sid=d9127df7-c4ed-400b-b8aa-74fc58c89bd2

Looking forward to your feedback :)

2024-01-05 17:19 UTC, yitongzhang commented
Hey, thanks for putting this up! This generally looks good the only thing missing is rounding the corners on the main card. After that feel free to merge!

2024-01-07 16:49 UTC, stepandel requested changes

2024-01-07 16:49 UTC, stepandel commented on src/lib/alligatorUtils.ts
wondering why this is part of this PR. Was this a bad merge that didn't pull latest changes from the`main`?

2024-01-07 16:49 UTC, stepandel commented on src/app/delegates/actions.ts
I like this

2024-01-07 16:49 UTC, stepandel commented on src/app/delegates/actions.ts
do you know why some functions have `"use server";` and some don't?

2024-01-08 11:32 UTC, ferrodri commented on src/lib/alligatorUtils.ts
I decided to add that default in the switch to follow the pattern of src/lib/config.ts
`export type Deployments = "optimism" | "nouns";

export const DEPLOYMENT_NAME = (process.env.NEXT_PUBLIC_AGORA_INSTANCE_NAME ||
  "optimism") as Deployments;
` Otherwise, the getProxyAddress function would return `Promise<string | undefined>` which I thought was adding unnecessary complexity to the code. However, I left a TODO since I thought a conversation was needed over what to do if `process.env.NEXT_PUBLIC_AGORA_INSTANCE_NAME` was missing

2024-01-08 11:35 UTC, ferrodri commented on src/app/api/voting-power/getVotingPower.ts
> -}): Promise<string | undefined> {
I did remove the undefined, please look at this comment https://github.com/voteagora/agora-next/pull/45#discussion_r1444483090

2024-01-08 12:01 UTC, ferrodri commented on src/app/delegates/actions.ts
I totally missed that when refactoring, thanks for bringing it up, now it is solved. Apart from that, I think we should consider refactoring server actions since some server actions definitions are repeated across the code, such as fetchDelegate, what do you think?

2024-01-08 12:26 UTC, ferrodri commented on src/components/DelegateStatement/DelegateStatementForm.tsx
> +      setDelegate(_delegate);
Hey Stepandel, but we need the wallet address that we get on the client from useAccount, how do you suggest doing a serverside component with the address which is data we get on the client? If we knew the address from the user ahead we could do this, but I think it is not the case.

2024-01-08 12:27 UTC, ferrodri commented on src/components/DelegateStatement/DelegateStatementForm.tsx
> +    const signature = await messageSigner
I did test it with a safe I have on goerli, is something wrong here?

2024-01-08 13:39 UTC, ferrodri commented on src/components/DelegateStatement/CurrentDelegateStatement.tsx
> +async function queryDynamoDB(address: string) {
I totally missed the DynamoDB statement was there, sorry for that, I already included the dynamoDB query. Refactor is in process on this commit: https://github.com/voteagora/agora-next/pull/45/commits/b6ce9cc9c0664f3da9d3988d5ee9360550a3a88e but I believe to do the complete refactor we need to tackle the DynamoDB/PostgreSQL logic on /delegates/[addressOrEnsName] page and in another section of the code. I will be happy to continue with this in a different PR, to not make this one huge

2024-01-08 13:39 UTC, ferrodri commented on src/components/DelegateStatement/CurrentDelegateStatement.tsx
> +      }
Some WIP has been done, please look at this comment: https://github.com/voteagora/agora-next/pull/45#discussion_r1444654572

2024-01-08 17:51 UTC, stepandel requested changes

2024-01-08 17:51 UTC, stepandel commented on src/app/api/delegateStatement/createDelegateStatement.ts
@ferrodri  Please make sure there's signature verification logic here before the statement is written to DB

2024-01-08 17:51 UTC, stepandel commented on src/app/api/delegateStatement/getDelegateStatement.ts
There're 2 ways delegate statement is being pulled right now. Make sure to consolidate them into 1 function that correctly determines which storage to pull the statement from

2024-01-08 17:51 UTC, stepandel commented on src/lib/alligatorUtils.ts
I'd rather have it throw than return an incorrect value

2024-01-08 17:51 UTC, stepandel commented on src/components/DelegateStatement/DelegateStatementForm.tsx
> +    const signature = await messageSigner
Just making sure. Also, please add verification logic on the backend (without verification there's no point of having a user to sign).
PS. make sure you test on OP mainnet

2024-01-08 17:51 UTC, stepandel commented on src/components/DelegateStatement/CurrentDelegateStatement.tsx
> +async function queryDynamoDB(address: string) {
Please make it part of this PR as it's the core functionality

2024-01-08 17:51 UTC, stepandel commented on src/app/delegates/actions.ts
that's a good suggestion but let's keep it separate from this PR

2024-01-08 17:51 UTC, stepandel commented on src/components/DelegateStatement/DelegateStatementForm.tsx
> +      setDelegate(_delegate);
You actually already do have a parent component in `/profile/page` that pulls delegate statement. Although be it a client side component (arguably, it's better to have it as a server side but let's focus on the core functionality by now).
I missed that but that's what I meant.

Please make sure you're not fetching the data more times than necessary

2024-01-08 23:15 UTC, ferrodri commented on src/app/api/delegateStatement/getDelegateStatement.ts
This is done on this commit https://github.com/voteagora/agora-next/pull/45/commits/442581ad5fefff21e3402f9064ac35839f962043

2024-01-08 23:30 UTC, ferrodri commented on src/lib/alligatorUtils.ts
this is solved on this commit: https://github.com/voteagora/agora-next/pull/45/commits/eb74642bfbea7fa3a0f7e0543c67cae2e3e7cbf7

2024-01-09 01:12 UTC, ferrodri commented on src/components/DelegateStatement/DelegateStatementForm.tsx
> +    const signature = await messageSigner
Hi Stepandel, verification logic is done on this commit https://github.com/voteagora/agora-next/pull/45/commits/4d975ba0ee8fa0bd7d48dc86f0e69e44e4530e51 . I have tested multiple times with a multisig on OP and it is working!

2024-01-09 01:12 UTC, ferrodri commented on src/app/api/delegateStatement/createDelegateStatement.ts
https://github.com/voteagora/agora-next/pull/45/commits/4d975ba0ee8fa0bd7d48dc86f0e69e44e4530e51

2024-01-11 20:23 UTC, ferrodri commented
https://linear.app/agora-app/issue/AGORA-1446/port-the-citizens-tab-over-from-voteoptimismio is done here @kent @yitongzhang just in case you wan to check the UI
<img width="460" alt="mobile" src="https://github.com/voteagora/agora-next/assets/29060919/5a831f1b-4dd2-4204-a614-59244993c147">
<img width="1918" alt="desktop" src="https://github.com/voteagora/agora-next/assets/29060919/bc9fe4f0-b23a-4ad6-b639-e09a83de4948">

2024-01-15 14:25 UTC, stepandel requested changes
@ferrodri found a couple of issues with creating & editing statements:
https://www.loom.com/share/c7e5cb074e064f3aa0d9c2729607ebb7

2024-01-15 17:00 UTC, kent commented
@ferrodri I also added in the database the table to hold the "special" addresses for Citizens and the like

![CleanShot 2024-01-15 at 11 58 38@2x](https://github.com/voteagora/agora-next/assets/12737/a1b7ab70-d3c0-40a6-bed6-dc93d317f189)

Can you update this PR to include the Citizen fetching via Prisma. 

Scope it to:

```
FROM 'address_metadata'
WHERE kind = 'citizen' 
AND dao_slug = 'OP'
```

2024-01-17 17:07 UTC, merged