Support EIP-1271 signatures
voteagora/agora-next pull request #558
Opened 2024-10-12 05:44 UTC by mdehoog

Ballot submission returns an error for smart contract wallets, because the regex enforces the signature to be 130 hex characters (65 bytes), but EIP-1271 signatures are often far longer than that.

This PR fixes the signature validation bug by removing the exact signature length validation.

Unfortunately the `ballotSubmittions.signature` column in the schema is a VARCHAR(255) which limits the ability to store full signatures in the database. Not sure what the downstream effects of this are, but I've updated the upsert to truncate the signature to fit in the column. If that breaks something downstream, we'll have to update the schema itself (i think https://github.com/voteagora/queries is a private repo?).

2024-10-12 17:28 UTC, mdehoog commented
@stepandel @yitongzhang any chance we can merge and deploy this before `Oct 14th 18:00 UTC`? I'm currently blocked on voting for round5, would love to get it in prior to the round close. Thanks.

2024-10-16 20:38 UTC, yitongzhang commented
Hey @mdehoog good to see you again. It's been a bit! Sorry we totally missed this PR last Friday. It was a hectic day. For time-sensitive issues, please ping us or the OP foundation directly on slack or via twitter DM's.

Just flagged this PR to our eng team to make sure they're aware and can address this issue.

2024-10-16 21:07 UTC, stepandel requested changes
please remove signature tranc and leave the zod validator changes.
Thank you!

2024-10-16 21:36 UTC, mdehoog commented on src/app/api/common/ballots/submitBallot.ts
> +
done, thanks!

2024-10-16 21:39 UTC, stepandel approved these changes
beauty, thank you!

2024-10-16 21:39 UTC, merged

2024-10-16 22:26 UTC, kent commented
Thank you @mdehoog, we are upping our GitHub repo notifications to make sure we don't sleep on these. Awesome to have you as our first non Agora contributor :) tysm